apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  labels:
    {{ .Values.labels | toYaml | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.fullname }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.fullname }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: tolgee
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 8080
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

    env:
      - name: TOLGEE_FILE_STORAGE_URL 
        value: {{ .Values.tolgee.fileStorageUrl }}
      - name: TOLGEE_FRONT_END_URL 
        value: {{ .Values.tolgee.frontEndUrl }}
      - name: TOLGEE_MAX_FILE_SIZE 
        value: {{ .Values.tolgee.maxUploadFileSize }}
      - name: TOLGEE_MAX_SCREENSHOTS_PER_KEY
        value: {{ .Values.tolgee.maxScreenshots }}
      - name: TOLGEE_MAX_UPLOAD_FILE_SIZE
        value: {{ .Values.tolgee.maxUploadFileSize }}