apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.tolgee.storage.existingClaim }}
spec:
  storageClassName: {{ .Values.tolgee.storage.storageClass }}
  accessModes:
    - {{ .Values.tolgee.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.tolgee.storage.size }}
