apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  labels:
    {{ .Values.labels | toYaml | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Values.fullname }}
    app.kubernetes.io/instance: {{ .Release.Name }}
